import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './index.css';
import { Providers } from '@/components/providers';
import { RootProvider } from '@/context/store-context';
import { HeaderPage } from '@/components/Header';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <RootProvider>
                    <Providers>
                        <HeaderPage />
                        {children}
                    </Providers>
                </RootProvider>
            </body>
        </html>
    );
}
